### ISSUE TITLE
Definition of enhancer

### ISSUE THREAD

**Issue by ytanaka-bio** [UCDNJJ/ucdnjj.github.io#1]
This BICCN challenge is very interesting topic.
I would like to know how the enhancer should be defined. ATAC-seq data may contain both promoter and enhancer peaks, but the goal is to identify cell type-specific "enhancer".  However, the instruction said "you should report the rank of top 10,000 peaks".  Does this mean that 1) we should report both promoter and enhancer peaks or 2) we should exclude promoter peaks and report only enhancer peaks?

**Comment by UCDNJJ** [comment]
For this challenge we have slightly abused the term "enhancer". You should feel free to propose any cis regulatory element (CRE) within the set of Mouse peaks when you build a ranked list for each subclass. 

Let me know if you have any other questions.

**Comment by ytanaka-bio** [comment]
Thanks. I got it!
